export const tagOptions =[
    'Fashion',
    'Electronics',
    'Real Estate',
    'Books & Movies',
    'Motors',
    'Software',
    'Home & Garden',
    'Health & Beauty',
    'Collectibles & Art',
    'Sport Goods',
    'Business & Industry',
    'Toy & Hobbies',
    'Other Items'

]

export const filterOptions= ['Vehicles',
'Bicycles','Automotive Hand Tools',
 'Boats','Other Vehicles & Trailers',
 'Automotive Part & Accessories',
 'Womens Clothing',
 'Womens Accessories',
  'Mens Clothing',
  'Mens Accessories',
  'Shoes',
  'Jewelry', 'Watches',
  'Parts & Accessories',
  'Kids Clothing,Shoes & Accessories',
  'Domain',
  'Web Application',
  'Mobile Application',
  'Desktop Application',
  'Other Application',
'Musical Instruments & Gear',
'DVD & Movies',
'Books',
'Musics', 
     'Computers, Tablets & Network Hardware',
     'Computers Parts & Accessories',
     'Cell Phones, Smart Watches & Accessories',
      'Video Games & Console',
      'Cameras & Photo',
      'TV, Video & Home Audio Electronics',
      'Portable Audio & Headphones',
      'Vehicle Electronics & GPS',
      'Multipurpose Power & Batteries',
       'Surveillance & Smart Home Electronics',
       'Old/Vintage Electronics',
       'Radio Communication Electronics',
        'Virtual Reality Headsets, Parts & Accessories',
     'Land',
     'Residential',
     'Commercial',
     'Shops',
     'Room',
      'Other Real Estate',
    'Art',
    'Collectibles',
    'Sports Card',
    'Paper Art & Craft Supplies',
    'Antiques',
    'Dolls & Teddy Bears',
    'Pottery & Glass',
    'Entertainment Memorabilia',
    'Stamps',
    'Yard, Garden & Outdoor Items',
     'Tools & Workshop Equipment',
     'Kitchen, Dinning & Bar Supples',
     'Home Improvement',
      'Household & Cleaning Supplies',
      'Camps, Lighting & Ceiling Fans',
       'Home Decor',
       'Home & Garden Furnitures',
       'Food & Beverages',
       'Major Appliances, Parts & Accessories',
        'Bedding',
        'Greeting Cards & Party Supplies',
        'Bathroom Supplies & Accessories',
        'Rugs & Carpets',
        'Window Treatments & Hardware',
        'Holiday & Seasonal Decor',
        'Wedding Supplies',
     'Outdoor Sports Equipment',
      'Hunting Equipment',
      'Fitness, Running & Yoga Equipment',
       'Cycling Equipment',
       'Golf Equipment',
       'Fishing Equipment & Supplies',
       'Tennis & Racquel Sports',
       'Water Sports Equipment',
       'Indoor Games',
       'Team Sports Equipment',
  'Action Figures',
  'RC Model Vehicles, Toys & Control Line',
  'Games',
  'Diecast & Toy Vehicles',
  'Collectible Card Games & Accessories',
  'Building Toys',
  'Model Railroads & Trains',
  'Toy Models & Kits',
  'Preschool Toys & Pretend Play',
  'Vintage & Antique Toys',
  'Outdoor Toys & Structures',
  'Slot Cars',
  'Puzzles',
  'Robot, Monster & Space Toys',
  'Electrical Equipment & Supplies'  ,
  'Health Care, Lab & Dental',
  'Wire & Metal Manufacturing',
  'Test, Measurement & Inspection Equipment',
  'Office Equipment & Supplies',
  'Industrial Automation & Motion Control',
  'Heavy Equipment, Parts & Attachments',
  'Material Handling',
  'Facility Maintenance & Safety Equipment',
  'Restaurant & Food Services',
  'Light Industrial Equipment & Tools',
  'Hydraulics, Pheumatics, Pumps & Plumbing',
  'Retail & Services',
  'Printing & Graphic Arts',
  'Industrial Fasteners(Screw), Bolts & Hardware',
  'HVAC & Refrigeration',
  'Building Materials & Supplies',
  'Agriculture Forestry Equipment',
    'Skin Care Products',
    'Vitamins & Dietary SUpplements',
    'Haircare & Styling Products',
    'Fragrances',
    'Makeup Products',
    'Health Care Products',
    'Medical & Mobility',
    'Shaving & Hair Removal Products',
    'Manicure, Pedicure & Nail Products',
    'Natural & Alternative Remedies',
    'Vision Care Products',
    'Oral Care Products',
    'Oral Cone Products',
    'Bath & Body Products',
    'Massage Equipment & Supplier' ,
    'Sun Protection & Tanning Equipment',
    'Tattoos & Body Art Products',
    'Tickets & Travels',
    'Gift Cards & Coupons',
    'Everything Else'
  ]
